<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="2">
  <testsuite name="" timestamp="2021-11-10T11:41:04" tests="0" file="cypress/integration/block-basics.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Root Suite.Blocks Tests" timestamp="2021-11-10T11:41:04" tests="1" time="0.0000" failures="2">
    <testcase name="&quot;before each&quot; hook: setupBeforeEach for &quot;Add Block: Empty&quot;" time="0.0000" classname="Blocks Tests">
      <failure message="`cy.request()` failed trying to load:

http://localhost:8080/Plone/@login

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ECONNREFUSED 127.0.0.1:8080

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:8080/Plone/@login

-----------------------------------------------------------

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Blocks Tests`" type="CypressError"><![CDATA[CypressError: `cy.request()` failed trying to load:

http://localhost:8080/Plone/@login

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:8080

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:8080/Plone/@login

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Blocks Tests`
    at http://localhost:3000/__cypress/runner/cypress_runner.js:140080:19
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:10791:23)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:5930:37
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:10791:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:8726:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:8783:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:8828:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:8904:18)
    at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:5498:12)
    at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:5491:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:5507:5)
    at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:5377:14)
From Your Spec Code:
    at Context.eval (http://localhost:3000/__cypress/tests?p=cypress/integration/block-basics.js:339:13)

From Node.js Internals:
  RequestError: Error: connect ECONNREFUSED 127.0.0.1:8080
      at new RequestError (/Users/nileshgulia/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)
      at Request.plumbing.callback (/Users/nileshgulia/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)
      at Request.RP$callback [as _callback] (/Users/nileshgulia/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)
      at self.callback (/Users/nileshgulia/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)
      at Request.emit (events.js:315:20)
      at Request.onRequestError (/Users/nileshgulia/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)
      at ClientRequest.emit (events.js:327:22)
      at Socket.socketErrorListener (_http_client.js:469:9)
      at Socket.emit (events.js:315:20)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
  ]]></failure>
    </testcase>
    <testcase name="&quot;after each&quot; hook: tearDownAfterEach for &quot;Add Block: Empty&quot;" time="0.0000" classname="Blocks Tests">
      <failure message="`cy.request()` failed trying to load:

http://localhost:8080/Plone/@login

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ECONNREFUSED 127.0.0.1:8080

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:8080/Plone/@login

-----------------------------------------------------------

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Blocks Tests`" type="CypressError"><![CDATA[CypressError: `cy.request()` failed trying to load:

http://localhost:8080/Plone/@login

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:8080

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:8080/Plone/@login

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Blocks Tests`
    at http://localhost:3000/__cypress/runner/cypress_runner.js:140080:19
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:10791:23)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:5930:37
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:10791:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:8726:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:8783:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:8828:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:8904:18)
    at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:5498:12)
    at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:5491:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:5507:5)
    at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:5377:14)
From Your Spec Code:
    at Context.eval (http://localhost:3000/__cypress/tests?p=cypress/integration/block-basics.js:339:13)

From Node.js Internals:
  RequestError: Error: connect ECONNREFUSED 127.0.0.1:8080
      at new RequestError (/Users/nileshgulia/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)
      at Request.plumbing.callback (/Users/nileshgulia/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)
      at Request.RP$callback [as _callback] (/Users/nileshgulia/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)
      at self.callback (/Users/nileshgulia/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)
      at Request.emit (events.js:315:20)
      at Request.onRequestError (/Users/nileshgulia/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)
      at ClientRequest.emit (events.js:327:22)
      at Socket.socketErrorListener (_http_client.js:469:9)
      at Socket.emit (events.js:315:20)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
  ]]></failure>
    </testcase>
  </testsuite>
</testsuites>